### ISSUE TITLE
Implement Observations

### ISSUE THREAD

**Issue by philipmjohnson** [agilegardenclub/public-garden#13]
Please do work for this task in a branch named issue-013.

Support observation data both within the data model and in the UI.

### Representation

Observations are always attached to a single "Planting Instance" (which can be uniquely identified via a tuple of (GardenID, Year, BedID, PlantID, and StartDate). In addition to the "Planting Instance" information, observations have their own date (we'll call it "ObservationDate"), a "description" (free text with additional details), an optional Picture, and one or more  "tags" (which provide additional information). 

### Tag types

So far, we have come up with the following tags:

1. Tag: "Pest".  This observation is useful because: (a) the gardener might choose to rotate beds for this Planting in future seasons, and other gardeners will find it useful to know in real time that the pest is present in their community.

2. Tag: "First Harvest" (as well as "Last Harvest").  These observations are useful to the gardener because it provides more detailed guidance on how long a particular PlantID needs to actually be in a bed.  Community members also will find this of use in their own garden planning. 

3. Tag: "First Frost" (as well as "Last Frost").  Again, this seems like it could be useful for planning purposes in future years to decide when it's safe to have certain plants in the garden  It could also be used to validate weather station data against the actual climate situation in the garden. Interestingly, if we want to get chapter-wide info on frost dates, we might have to communicate that one gardener observed a frost event to all the other gardeners in the chapter and ask them to confirm/deny frost in their garden (this disambiguates the "no frost" from "no data" situation.)

4. Tag: "Disease" - different than pest, which is animal specific.  Disease might be leaf curl, wilts etc.

5. Tag: "Companion" - I think it would be interesting to see examples of plants benefitting from each other.  For example, plants vining on each other, providing shade, protecting from pests.

6. Tag: "Trellis" or "Plant support" - Might not be the right tags, but Jessie once brought up that she would love to see examples of how other gardeners trellis/support plants and I think there could be good learning from sharing of these systems.

7. Tag: "Planting Technique". That makes me think about planting strategies in general.  I just planted potatoes for the first time and went online to see how best to do that.  There are many ways to plant potatoes.  Unknown if there are ways more suited for my climate or the type of potato I planted.  I could imagine using the app to peruse pictures of potato planting strategies, perhaps even filtering by variety, to get support for this process.  Maybe the tag is "Planting technique"

8. Tag: "First leaf", "First bud", "First Flower", "First seed" (Phenology).  These tags make patterns in climate change obvious as well as provide insight into how two garden's climates might differ.  For example, Jessie and I both have the same kind of raspberry.  Knowing if her raspberry flowers/fruits/leafs out etc earlier or later than mine can explain to me other differences in our garden's performance.

9. Tag: "Aesthetic".  In addition to the above "useful" tags, we also think it's important to have a final category of tag that indicates an observation that the gardener thinks is interesting even if it's not particularly actionable.  (These observations can be filtered out by other gardeners if they don't want to see them.) 

In addition, there are a couple of tags that provide "meta" information:

10: Tag: "Public". Indicate if an observation can appear on the public page. 

11. Tag: "Help wanted". Indicates if the Observation describes an issue or problem for which the gardener needs help. For example, "What is this pest?"

### Observations can be conversations

Finally, all observations provide a "Reply" button in the app. This means that any and all Observations can trigger conversations within the community.

**Comment by Jennacd** [comment]
I propose we combine tags #5-6 into a tag called "technique"

**Comment by philipmjohnson** [comment]
Examples of Observations now available in the public interface.
