### ISSUE TITLE
Improve Garden Summary card

### ISSUE THREAD

**Issue by philipmjohnson** [agilegardenclub/public-garden#14]
Please do work for this task in a branch named issue-014.

The garden summary card should be computed from the data:

* Number of years
* Number of beds
* Number of plants
* Number of plantings
* Number of observations

**Comment by Jennacd** [comment]
Could this be where the lifetime list of plants grown is located?

**Comment by Jennacd** [comment]
Pull out garden map from carousel and put it in it's own block
