### ISSUE TITLE
Improve Gardener representation

### ISSUE THREAD

**Issue by philipmjohnson** [agilegardenclub/public-garden#15]
Please do work for this task in a branch named issue-015.

Add to the gardener representation:

* publicImage
* publicDescription
* publicAlias

Then update the badge to include the publicImage and publicAlias. Clicking on the badge pops up a card that specifies:

* Number of years
* Number of gardens
* Number of plants
* Number of plantings
* Number of beds
* Number of observations

We also have the idea of badges for gardeners, such as:
* Master Gardener
* "Super seed saver" (with bronze, silver, gold levels depending upon achievements)

**Comment by Jennacd** [comment]
Other badges ideas: (we can workshop names)
-  <Plant type> Club ->for example "Tomato Club" for growing X varieties of tomatoes in lifetime
-  Diversity Champion <year> ->for growing X types of plants in a year
