### ISSUE TITLE
Updates to timeline

### ISSUE THREAD

**Issue by Jennacd** [agilegardenclub/public-garden#23]
Please do work for this task in a branch named issue-023.

Updates to timeline section of public view:

- [x] Fix bug in Jessie's data for 2020 that lists beds out of order.
- [x] Add By Vendor filter.
- [x] Change data model to use varietalID rather than plantID.
- [x] Rename By Plant to By Varietal.
- [x] Rename "PlantFamily" to "Family"
- [x] Add new data model concept: Crop
- [x] Add "By Crop" filter
- [x] Make sure all filter drop-down labels are sorted alphabetically. 
- [x] Dropdown for both public gardens in agc.com
- [x] Remove familyID from varietals.
- [x] Add crop badges to chapter
- [x] Renamed "varietal" to "variety"
- [x] Fixed bug in Jessie's observation data (moved observations to her garden object)
- [x] WeekCol does not know the year, so is displaying all observations across all years. 
- [x] Added gap in timeline to indicate current week of current year.
- [ ] Plants are grouped first by bed, then by crop, then variety, then by date (earliest to latest planted).
- [ ] Plants associated with a given crop in a bed can be collapsed
- [ ] TBD varietals
- [ ] Notifications appear twice.

**Comment by philipmjohnson** [comment]
1. "out of order" bug was because beds are sorted alphabetically, and were named "1", "2", "3" rather than "01", "02", "03".
