### ISSUE TITLE
Climate widget

### ISSUE THREAD

**Issue by Jennacd** [agilegardenclub/public-garden#41]
Please do work for this task in a branch named issue-041.

Create a widget that provides garden-relevant climate data and allows a gardener to filter different ways to get different kinds of insights.  As a start, it would be interesting to be able to:
-See what is happening locally at a month scale
-Compare months of one year to the same month of a different year
-Compare one year to another year, find similar years
Relevant data:
-soil temperature
-temperature highs and lows
-rainfall

**Comment by philipmjohnson** [comment]
Integrated this into Issue #10
