### ISSUE TITLE
Create script to pull useful monthly climate data from Avazea

### ISSUE THREAD

**Issue by philipmjohnson** [agilegardenclub/public-garden#50]
Climate data changes.... slowly.   For AGC, we are interested in climate data at the grain size of months, so the most often we would want to access climate data is once a month. 

Avazea seems like it might be a good source of climate information for AGC.  To test this hypothesis, it would be very helpful to create a script (either bash script or npm) that when provided with appropriate credentials, accesses the Avazea API and writes out a JSON file containing climate data useful for AGC. 

This script (or scripts) can be stored in its own repo within the agilegardenclub organization (i.e. climatedata).

**Comment by mercedezcastro** [comment]
1st version: https://github.com/agilegardenclub/climate-data
