### ISSUE TITLE
Seed saving features

### ISSUE THREAD

**Issue by Jennacd** [agilegardenclub/public-garden#67]
Please do work for this task in a branch named issue-067.

Check box in planting: seeds saved
Check box: shareable seeds
In planting card it notes that seeds were saved as well as available to chapter (shareable)
In chapter and garden overview, list of seeds available at a crop level.  Click crop and it lists the varieties

Use this data:
planting-022.3 (scarlet runner beans, no change to end harvest)
planting-101, add end harvest June 15, 2022 (flashy troutback lettuce)

**Comment by philipmjohnson** [comment]
The check boxes are implemented; the overviews show planting badges not a crop badge (because that was easier to implement and I think is good enough for demo purposes. 

Also added tooltips to the timeline as a special treat.
