### ISSUE TITLE
Fix duplicate planting IDs, fix invalid dates

### ISSUE THREAD

**Issue by philipmjohnson** [agilegardenclub/public-garden#93]
Please do work for this task in a branch named issue-XXX.

## Fix duplicate planting IDs

In gardenData.js, all of the "planting-ID"s must be unique. Unfortunately, a bunch of duplicates have crept in which make data migration difficult. 

Please fix the following duplicates.  Perhaps the easiest way is to add an alphabetic suffix such as "-a", "-b", "-c", "-d". To guarantee you don't inadvertently create a new duplicate, don't reuse the suffix. (when you get to "-z", then go on to "-aa", "-ab", etc.

Here are the duplicates that I am aware of.
* 011.05
* 022.1
* 022.2
* 022.3
* 022.4
* 302

## Fix invalid dates

All dates must be in the format dd/MM/yyyy

planting-2004 has an invalid firstHarvestDate.

## Note

You can wait to do this until you are making an update to the gardenData file.

**Comment by Jennacd** [comment]
@philipmjohnson Sorry I've been absorbed by Dart I let this slip.  It's done now.
